package model.pojo;
// Generated Oct 16, 2022 9:28:00 PM by Hibernate Tools 4.3.1

import DAO.DAODaftar;
import java.sql.ResultSet;
import java.util.List;
import javax.faces.bean.ManagedBean;


/**
 * RegistrationData generated by hbm2java
 */
@ManagedBean
public class RegistrationData  implements java.io.Serializable {


     private Integer idDaftar;
     private String namaLengkap;
     private int nik;
     private String alamat;
     private int noHp;
     private String email;
     private String vaksin;
     private String tanggal;
     
    public String save_Daftar()
    {
        DAODaftar add = new DAODaftar();
        add.add_product(this);
        return "Berhasil";
    }
    
    public List<RegistrationData> getDatadaftar()
    {
        DAODaftar regis = new DAODaftar();
        List <RegistrationData> rd = regis.retrevetabelregis();
        return rd;
    }
    
     public String getByIddf()
    {
        String id_daftar = idDaftar.toString();
        DAODaftar rd = new DAODaftar();
        List<RegistrationData> lRd = rd.getbyID(idDaftar);
        namaLengkap = lRd.get(0).getNamaLengkap();
        nik = lRd.get(0).getNik();
        alamat = lRd.get(0).getAlamat();
        noHp = lRd.get(0).getNoHp();
        email = lRd.get(0).getEmail();
        vaksin = lRd.get(0).getVaksin();
        tanggal = lRd.get(0).getTanggal();
        return"Admin";
    }

     
    public String edit_daftar(){
        DAODaftar df = new DAODaftar();
        df.editDaftar(this);
        namaLengkap = "";
        nik = 0;
        alamat = "";
        noHp = 0;
        email = "";
        vaksin ="";
        tanggal="";
        return "Admin";
    }
    
    public String delete_daftar(){
        DAODaftar df = new DAODaftar();
        df.deleteDaftar(idDaftar);
        namaLengkap = "";
        nik = 0;
        alamat = "";
        noHp = 0;
        email = "";
        vaksin ="";
        tanggal="";
        return "Admin";
    } 
    
    public String reset_daftar(){
        DAODaftar df = new DAODaftar();
        df.resetDaftar(this);
        namaLengkap = "";
        nik = 0;
        alamat = "";
        noHp = 0;
        email = "";
        vaksin ="";
        tanggal="";
        return "Daftar Vaksin";
    }
    
    public String reset_daftarAdmin(){
        DAODaftar df = new DAODaftar();
        df.resetDaftar(this);
        namaLengkap = "";
        nik = 0;
        alamat = "";
        noHp = 0;
        email = "";
        vaksin ="";
        tanggal="";
        return "Admin";
    }

    public RegistrationData() {
    }

    public RegistrationData(String namaLengkap, int nik, String alamat, int noHp, String email, String vaksin, String tanggal) {
       this.namaLengkap = namaLengkap;
       this.nik = nik;
       this.alamat = alamat;
       this.noHp = noHp;
       this.email = email;
       this.vaksin = vaksin;
       this.tanggal = tanggal;
    }
   
    public Integer getIdDaftar() {
        return this.idDaftar;
    }
    
    public void setIdDaftar(Integer idDaftar) {
        this.idDaftar = idDaftar;
    }
    public String getNamaLengkap() {
        return this.namaLengkap;
    }
    
    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap = namaLengkap;
    }
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public int getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(int noHp) {
        this.noHp = noHp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getVaksin() {
        return this.vaksin;
    }
    
    public void setVaksin(String vaksin) {
        this.vaksin = vaksin;
    }
    public String getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }


}


